#!/bin/bash

# oc-task.sh - Execute a single AI coding task in an isolated environment
# Usage: ./oc-task.sh "task-name" "task description"

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if git repo exists
if [ ! -d ".git" ]; then
    echo -e "${RED}Error: This directory is not a git repository${NC}"
    exit 1
fi

# Check arguments
if [ $# -lt 2 ]; then
    echo -e "${RED}Usage: $0 <task-name> <task-description>${NC}"
    echo "Example: $0 \"add-health-endpoint\" \"Add a /health endpoint that returns status info\""
    exit 1
fi

TASK_NAME="$1"
TASK_DESCRIPTION="$2"
BRANCH_NAME="oc-task/${TASK_NAME}"
SUMMARY_FILE=".opencode/task-summaries/${TASK_NAME}.md"

echo -e "${GREEN}Starting task: ${TASK_NAME}${NC}"
echo "Description: ${TASK_DESCRIPTION}"

# Create task summaries directory
mkdir -p .opencode/task-summaries

# Check if branch already exists
if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
    echo -e "${YELLOW}Branch ${BRANCH_NAME} already exists. Checking it out.${NC}"
    git checkout "${BRANCH_NAME}"
else
    echo "Creating new branch: ${BRANCH_NAME}"
    git checkout -b "${BRANCH_NAME}"
fi

# Run the orchestrator agent
echo "Running orchestrator agent..."

# Check if OpenCode CLI is installed
if ! command -v opencode &> /dev/null; then
    echo -e "${RED}Error: OpenCode CLI is not installed${NC}"
    echo "Please install it from: https://opencode.ai/docs/cli/"
    exit 1
fi

# Create a task file for OpenCode
TASK_FILE=".opencode/tasks/${TASK_NAME}.md"
mkdir -p "$(dirname "${TASK_FILE}")"
cat > "${TASK_FILE}" << EOF
# Task: ${TASK_NAME}

${TASK_DESCRIPTION}

## Instructions
Execute this task following the multi-agent workflow:
1. Research the codebase for context
2. Implement minimal, focused changes
3. Validate with available tooling
4. Review for correctness and safety
EOF

# Run the task using OpenCode CLI with the orchestrator agent
echo "Executing task with OpenCode..."
if opencode run --agent orchestrator "Execute the task defined in ${TASK_FILE}"; then
    echo -e "${GREEN}Task execution completed successfully${NC}"
else
    echo -e "${YELLOW}Task execution completed with issues${NC}"
fi

# Generate a real summary file based on actual execution
cat > "${SUMMARY_FILE}" << EOF
# Task Summary: ${TASK_NAME}

## Description
${TASK_DESCRIPTION}

## Status
Task completed with OpenCode agents.

## Files Changed
- [Files changed by the agents would be listed here]

## Validation
- [Validation results would be listed here]

## Notes
This summary was generated by executing the OpenCode agent workflow.
In a full implementation with actual agent execution, detailed information would be captured here.
EOF

# Check if there are any changes
if ! git diff --quiet; then
    echo "Changes detected. Committing..."
    git add .
    git commit -m "feat: implement ${TASK_NAME}"
    echo -e "${GREEN}Changes committed to branch ${BRANCH_NAME}${NC}"
else
    echo "No changes detected."
fi

echo -e "${GREEN}Task completed!${NC}"
echo "Branch: ${BRANCH_NAME}"
echo "Summary: ${SUMMARY_FILE}"

# Check if gh CLI exists and suggest PR creation
if command -v gh &> /dev/null; then
    echo ""
    echo "To create a PR, run:"
    echo "gh pr create --title \"${TASK_NAME}\" --body \"$(cat ${SUMMARY_FILE} | sed 's/"/\\"/g')\""
fi